always_on_subgrid_rgba:
- 1.0
- 1.0
- 1.0
- 0.3
always_show_subgrid: false
app_version: 0.2.1
background_rgba:
- 0.0
- 0.0
- 0.0
- 0.35
classname: AppConfig
font_size_multiplier: 0.5
grid_defn:
- border_width: 0.0
  callback: build_cell_strings
  num_cells_x: 16
  num_cells_y: 1
- border_width: 1.0
  callback: build_cell_strings
  num_cells_x: 1
  num_cells_y: 16
- border_width: 0.0
  callback: apply_strings_and_subgrid_to_cells
  num_cells_x: 2
  num_cells_y: 1
grid_rgba:
- 0.9
- 1.0
- 1.0
- 1.0
hide_cursor_on_click: true
hide_location: bottom_left
keymap:
  close dialog: AltRight
  cycle click count: null
  cycle mouse action type: null
  cycle mouse button: null
  edit config: Tab
  execute mouse action: Space
  hide overlay: AltRight
  hold for drag: CommandLeft
  hold for move: AltLeft
  hold for right button: CommandRight
  release hold/drag: AltRight
  repeat last mouse action: null
  show overlay: CommandLeft tap
  switch monitor left: ShiftLeft tap
  switch monitor right: ShiftRight tap
  toggle overlay: null
mouse_action_keys: ABCDEFGHIJKLMNOPQRSTUVWXYZ
move_duration_ms: 100
move_real_cursor_with_virtual: true
multi_action_timeout_ms: 400
strategy: subgrid
subgrid_dims:
- 8
- 3
subgrid_font_size_multiplier: 0.9
subgrid_mouse_action_keys: QWERUIOPASDFJKL;ZXCVM,./
subgrid_rgba:
- 1.0
- 1.0
- 1.0
- 0.9
subgrid_text_rgba:
- 1.0
- 1.0
- 1.0
- 0.5
tap_threshold_ms: 200
text_rgba:
- 1.0
- 1.0
- 1.0
- 0.65
window_opacity: 0.6
