#!/bin/zsh

BREW_FORMULAE=(
  docker
  eza
  fd
  feh
  ffmpeg
  fzf
  gcc
  git
  htop
  imagemagick
  istat-menus
  jq
  lazygit
  mas
  neovim
  pandoc
  rclone
  ripgrep
  starship
  stow
  tmux
  trash
  tree
  tree-sitter
  webp
  wget
  yarn
  yazi
  zoxide 
)

BREW_CASKS=(
  1password 
  bartender
  blender
  caffeine
  chatgpt
  dropbox
  gimp
  google-chrome
  istat-menus
  jupyterlab 
  karabiner-elements
  kindle
  kitty
  microsoft-auto-update
  microsoft-office
  microsoft-remote-desktop
  middleclick
  min
  neofetch
  obsidian
  positron
  raycast
  rstudio
  slack
  todoist
  visual-studio-code
  xquartz
  zoom
)

# install homebrew
if ! command -v brew &> /dev/null; then
  echo "installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  echo "updating homebrew..."
  brew update
fi

# taps
brew tap homebrew/cask-fonts
brew install font-tex-gyre-pagella
brew install font-tex-gyre-termes
brew install font-meslo-lg-nerd-font

brew tap r-lib/rig
brew install --cask rig

brew install --cask nikitabobko/tap/aerospace

brew install koekeishiya/formulae/skhd
skhd --start-service

# install formulae
echo "installing brew packages..."
for formula in "${BREW_FORMULAE[@]}"; do
  brew install "$formula" || echo "$formula is already installed"
done

# install casks
echo "installing brew apps..."
for cask in "${BREW_CASKS[@]}"; do
  brew install --cask "$cask" || echo "$cask is already installed"
done

echo "brew setup complete!"

# Remove outdated versions from the cellar.
brew cleanup

