#!/bin/zsh

BREW_FORMULAE=(
  bash
  bat
  docker
  eza
  fd
  feh
  ffmpeg
  fzf
  gcc
  git
  htop
  imagemagick
  istat-menus
  jq
  lazygit
  lua
  luarocks
  neovim
  node
  pandoc
  r
  rclone
  ripgrep
  rust
  starship
  stow
  tmux
  trash
  tree
  tree-sitter
  webp
  wget
  yarn
  yazi
  zoxide
)

BREW_CASKS=(
  1password
  appcleaner
  bartender
  blender
  chatgpt
  cmake
  gimp
  google-chrome
  istat-menus@6
  jupyterlab
  karabiner-elements
  kitty
  microsoft-auto-update
  microsoft-office
  microsoft-remote-desktop
  min
  notchnook
  obsidian
  positron
  postman
  raycast
  rstudio
  sf-symbols
  skim
  slack
  todoist
  via
  visual-studio-code
  xquartz
  zoom
)

# install homebrew
if ! command -v brew &> /dev/null; then
  echo "installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  echo "updating homebrew..."
  brew update
fi

# taps
brew tap homebrew/cask-fonts
brew install font-tex-gyre-pagella
brew install font-tex-gyre-termes
brew install font-meslo-lg-nerd-font

brew tap r-lib/rig
brew install --cask rig

brew install --cask nikitabobko/tap/aerospace

brew install koekeishiya/formulae/skhd
skhd --start-service

brew install --cask --no-quarantine middleclick

brew tap theseal/ssh-askpass
brew install ssh-askpass
sudo ln -s /usr/local/bin/ssh-askpass /usr/X11R6/bin/ssh-askpass

# install formulae
echo "installing brew packages..."
for formula in "${BREW_FORMULAE[@]}"; do
  brew install "$formula" || echo "$formula is already installed"
done

# install casks
echo "installing brew apps..."
for cask in "${BREW_CASKS[@]}"; do
  brew install --cask "$cask" || echo "$cask is already installed"
done

echo "brew setup complete!"

# Remove outdated versions from the cellar.
brew cleanup
