#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"

PLUGIN_DIR="$HOME/.config/sketchybar/plugins-laptop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

# SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

/opt/homebrew/bin/sketchybar --bar \
    height=32 \
    color=0x00000000 \
    margin=0 \
    sticky=on \
    padding_left=15 \
    padding_right=15 \
    notch_width=200 \
    display=main

# Alternatiive background colors
# label.color=0xffffffff
# background.color=0x9924273a
/opt/homebrew/bin/sketchybar --default \
    background.color=0x66494d64 \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Medium:16.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.font="SF Pro:Regular:16.0" \
    label.color=0xffcad3f5 \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=5

# /opt/homebrew/bin/sketchybar --add event spotify_change $SPOTIFY_EVENT \
#     --add item spotify e \
#     --set spotify \
#     icon= \
#     icon.y_offset=1 \
#     icon.font="$FONT_FACE:Bold:20.0" \
#     label.drawing=off \
#     label.padding_left=3 \
#     script="$PLUGIN_DIR/spotify.sh" \
#     --subscribe spotify spotify_change mouse.clicked

# /opt/homebrew/bin/sketchybar --add item current_space right \
#     --set current_space \
#     background.color=0xfff5a97f \
#     icon.color=0xff24273a \
#     label.drawing=off \
#     script="$PLUGIN_SHARED_DIR/current_space.sh" \
#     --subscribe current_space space_change mouse.clicked

# /opt/homebrew/bin/sketchybar --add item front_app right \
#     --set front_app \
#     background.color=0xffa6da95 \
#     background.padding_left=0 \
#     background.padding_right=0 \
#     icon.y_offset=1 \
#     icon.color=0xff24273a \
#     label.drawing=no \
#     script="$PLUGIN_SHARED_DIR/front_app.sh" \
#     --add item front_app.separator left \
#     --set front_app.separator \
#     background.color=0x00000000 \
#     background.padding_left=-3 \
#     icon= \
#     icon.color=0xffa6da95 \
#     icon.font="$FONT_FACE:Bold:20.0" \
#     icon.padding_left=0 \
#     icon.padding_right=0 \
#     icon.y_offset=1 \
#     label.drawing=no \
#     --add item front_app.name left \
#     --set front_app.name \
#     background.color=0x00000000 \
#     background.padding_right=0 \
#     icon.drawing=off \
#     label.font="$FONT_FACE:Bold:12.0" \
#     label.drawing=yes

# /opt/homebrew/bin/sketchybar --add bracket front_app_bracket \
#     front_app \
#     front_app.separator \
#     front_app.name \
#     --subscribe front_app front_app_switched

/opt/homebrew/bin/sketchybar --add item clock q \
    --set clock \
    icon=󰃰 \
    icon.color=0xffed8796 \
    update_freq=1 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

/opt/homebrew/bin/sketchybar --add item battery q \
    --set battery \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"

/opt/homebrew/bin/sketchybar --add item volume q \
    --set volume \
    icon.color=0xff8aadf4 \
    label.drawing=true \
    script="$PLUGIN_SHARED_DIR/volume.sh" \
    --subscribe volume volume_change

/opt/homebrew/bin/sketchybar --add item cpu q \
                             --set cpu  update_freq=2 \
                                        icon=􀧓  \
                                        script="$PLUGIN_SHARED_DIR/cpu.sh"

/opt/homebrew/bin/sketchybar --add item weather q \
    --set weather \
    icon= \
    icon.color=0xfff5bde6 \
    icon.font="$FONT_FACE:Bold:16.0" \
    update_freq=1800 \
    script="$PLUGIN_SHARED_DIR/weather.sh" \
    --subscribe weather system_woke

/opt/homebrew/bin/sketchybar --add item media q \
                             --set media \ #label.color=0xffed8796 \
                                         label.max_chars=20 \
                                         icon.padding_left=10 \
                                         scroll_texts=on \
                                         icon=􀑪             \
                                         icon.color=0xffed8796   \
                                         background.drawing=on \
                                         script="$PLUGIN_SHARED_DIR/media.sh" \
                             --subscribe media media_change

# /opt/homebrew/bin/sketchybar --add item weather.moon left \
#     --set weather.moon \
#     background.color=0x667dc4e4 \
#     background.padding_right=-1 \
#     icon.color=0xff181926 \
#     icon.font="$FONT_FACE:Bold:22.0" \
#     icon.padding_left=4 \
#     icon.padding_right=3 \
#     label.drawing=off \
#     --subscribe weather.moon mouse.clicked

export BAR_COLOR=0xff101314
export ITEM_BG_COLOR=0xff353c3f
export ACCENT_COLOR=0xffffffff

/opt/homebrew/bin/sketchybar --add item front_app e \
                             --set front_app      \ #background.color=$ACCENT_COLOR \
                                                   icon.color=$ACCENT_COLOR \
                                                   icon.font="sketchybar-app-font:Regular:16.0" \
                                                   label.color=$ACCENT_COLOR \
                                                   script="$PLUGIN_SHARED_DIR/front_app.sh"            \
                             --subscribe front_app front_app_switched


/opt/homebrew/bin/sketchybar --add item space_separator e                            \
                             --set space_separator icon="􀆊"                                \
                                                   icon.color=$ACCENT_COLOR \
                                                   icon.padding_left=4                   \
                                                   label.drawing=off                     \
                                                   background.drawing=off                \
                                                   script="$PLUGIN_SHARED_DIR/space_windows.sh" \
                             --subscribe space_separator space_windows_change     

SPACE_SIDS=(1 2 3 4 5 6 7)

for sid in "${SPACE_SIDS[@]}"
do
  /opt/homebrew/bin/sketchybar --add space space.$sid e                              \
                               --set space.$sid space=$sid                                 \
                                                icon=$sid                                  \
                                                   icon.color=$ACCENT_COLOR \
                                                label.font="sketchybar-app-font:Regular:16.0" \
                                                label.padding_right=20                     \
                                                label.y_offset=-1                          \
                                                script="$PLUGIN_SHARED_DIR/space.sh"              
done





# osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
/opt/homebrew/bin/sketchybar --update
/opt/homebrew/bin/sketchybar --trigger space_change
