#!/bin/bash

config_git() {
  cp ~/dotfiles/git/.extra.template .extra.sh
  gedit .extra.sh
  bash .extra.sh
}

install_packages() {
  ~/dotfiles/apt/apt
}

get_obsidian_vault() {
  git clone git@github.com:shawntschwartz/obsidian.git ~/documents/obsidian
}

make_neofetch() {
  sudo make -C ~/dotfiles/src/neofetch PREFIX=/usr/local install
}

create_dirs() {
  ~/dotfiles/files/setup
}

stow_dotfiles() {
  ~/dotfiles/stow/stow
}

start_zsh() {
##### set default shell #####
  zsh
  zsh-newuser-install -f
  chsh -l
  chsh -s /usr/bin/zsh
  
##### install oh my zsh #####
sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
}

confirm_reboot() {
  echo "[IMPORTANT] - it's now time to reboot... press <return> to continue or ctrl+c to cancel."
  read -r
  sudo reboot
}

printf "🐙  configuring git...\n"
#config_git

printf "🗄  creating directories and configuring files...\n"
#create_dirs

printf "🍺  brewing packages...\n"
#install_packages

printf "😇  stowing dotfiles...\n"
stow_dotfiles

printf "💎  getting obsidian vault...\n"
get_obsidian_vault

#start_zsh

printf "✨  order up, ubuntu is ready!!\n"
confirm_reboot

