#!/bin/bash

config_git() {
  cp ~/dotfiles/git/.extra.template .extra.sh
  gedit .extra.sh
  bash .extra.sh
}

install_packages() {
  ~/dotfiles/apt/apt
}

get_obsidian_vault() {
  git clone git@github.com:shawntschwartz/obsidian.git ~/documents/obsidian
}

make_neofetch() {
  sudo make -C ~/dotfiles/src/neofetch PREFIX=/usr/local install
}

create_dirs() {
  ~/dotfiles/files/setup
}

stow_dotfiles() {
  ~/dotfiles/stow/stow
}

confirm_reboot() {
  echo "[IMPORTANT] - it's now time to reboot... press <return> to continue or ctrl+c to cancel."
  read -r
  sudo reboot
}

printf "🐙  configuring git...\n"
config_git

printf "🗄  creating directories and configuring files...\n"
create_dirs

printf "🍺  brewing packages...\n"
install_packages

#printf "👨🏼‍💻  building neofetch from source...\n"
#make_neofetch

printf "😇  stowing dotfiles...\n"
stow_dotfiles

printf "💎  getting obsidian vault...\n"
get_obsidian_vault

printf "✨  order up, ubuntu is ready!!\n"
confirm_reboot

