#!/usr/bin/env bash

blazing_fast_keyboard() {
  gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 10
  gsettings set org.gnome.desktop.peripherals.keyboard delay 150
}

config_git() {
  cp ~/dotfiles/git/.extra.template .extra.sh
  gedit .extra.sh
  bash .extra.sh
}

install_packages() {
  ~/dotfiles/packages
}

get_obsidian_vault() {
  git clone git@github.com:shawntschwartz/obsidian.git ~/documents/obsidian
}

create_dirs() {
  ~/dotfiles/dirs
}

stow_dotfiles() {
  ~/dotfiles/stow
}

start_zsh() {
##### set default shell #####
  rm ~/.bash_history ~/.bash_logout ~/.bashrc

##### install oh my zsh #####
  sh -c "$(wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh -O -)"
  
  rm .zshrc
  mv .zshrc.pre-oh-my-zsh .zshrc
  source ~/.zshrc

  zsh
  chsh -s /usr/bin/zsh
}

confirm_reboot() {
  echo "[IMPORTANT] - it's now time to reboot... press <return> to continue or ctrl+c to cancel."
  read -r
  sudo reboot
}

blazing_fast_keyboard

printf "🐙  configuring git...\n"
config_git

printf "🗄  creating directories and configuring files...\n"
create_dirs

printf "🍺  brewing packages...\n"
install_packages

printf "😇  stowing dotfiles...\n"
stow_dotfiles

printf "💎  getting obsidian vault...\n"
get_obsidian_vault

start_zsh

printf "✨  order up, ubuntu is ready!!\n"
confirm_reboot

