#!/bin/zsh

DOTFILES=~/dotfiles

STOW=("aerospace" "hammerspoon" "karabiner" "kitty" "neofetch" "nvim" "raycast" "rstudio" "ssh" "starship" "tmux" "wallpapers" "yazi" "zsh")

cd "$DOTFILES" || exit

sudo -v

for DIR in "${STOW[@]}"; do
  echo "[INFO] - stowing $DIR..."
  sudo /opt/homebrew/bin/stow --verbose --target="$HOME" "$DIR"
done

echo "[INFO] - dotfiles stowed successfully!"
