#!/bin/zsh

DOTFILES=~/dotfiles

STOW=("aerospace" "karabiner" "kitty" "neofetch" "nvim" "starship" "tmux" "wallpapers" "yazi" "zsh")

cd "$DOTFILES" || exit

for DIR in "${STOW[@]}"; do
  echo "[INFO] - stowing $DIR..."
  stow --verbose --target="$HOME" "$DIR"
done

echo "[INFO] - dotfiles stowed successfully!"

