#!/bin/zsh

sudo -v

# for dir in $(ls $HOME)
# do
  # sudo mv $HOME/$dir $(echo $HOME/$dir | tr '[:upper:]' '[:lower:]')
  # echo "[INFO] - renamed $HOME/$dir"
# done

echo "[INFO] - making dirs..."
mkdir -p ~/Developer/repos
mkdir -p ~/Developer/projects
mkdir ~/Pictures/screenshots
# mkdir -p ~/Work
# mkdir -p ~/work/oss
# mkdir -p ~/work/analyses
# mkdir -p ~/work/teaching

echo "[INFO] - finished configuring home directory!"
