#!/usr/bin/env bash

echo "[install transfuse (kde plasma backup)]..."

cd ~/dotfiles/crontab || exit

curl -O https://gitlab.com/cscs/transfuse/-/raw/master/transfuse.sh

chmod +x transfuse.sh

./transfuse.sh -b `whoami`
